namespace Cooler_Box
{
    public class BlacklistedItems
    {
        public static string[] blacklistedItems = {
            "cooler",
            "motor oil",
            "coolant",
            "fire extinguisher",
            "two stroke fuel",
            "battery",
            "wheel cover",
            "dash cover",
            "seat cover",
            "beer case",
            "charcoal",
            "car jack",
            "ratchet set",
            "spanner set",
            "warning triangle",
            "gasoline",
            "diesel",
            "helmet",
            "digging bar",
            "radio",
            "xmas lights",
            "garbage barrel",
            "bucket",
            "basketball",
            "ax",
            "dipper",
            "water bucket",
            "fish trap",
            "lantern",
            "sofa",
            "wheel",
            "cylinder head",
            "gearbox",
            "oilpan",
            "block",
            "gauges",
            "carburator",
            "headers",
            "flywheel",
            "radiator",
            "steering wheel",
            "exhaust",
            "muffler",
            "seat",
            "strut",
            "coil spring",
            "shock absorber",
            "subframe",
            "bootlid",
            "hood",
            "grille",
            "brake lining",
            "gear linkage",
            "center console",
            "steering",
            "fuel tank",
            "halfshaft",
            "fender",
            "door",
            "dashboard",
            "panel",
            "handbrake",
            "gear stick",
            "head gasket",
            "rocker shaft",
            "rocker cover",
            "airfilter",
            "camshaft",
            "bumper",
            "subwoofer",
            "amplifier",
            "window black wrap",
            "windshield",
            "n2o",
            "wheel",
            "spoiler",
            "side skirt",
            "harness",
            "fuel strainer",
            "electrics",
            "hose",
            "trail arm",
            "grill"
        };
    }
}
